__opapp_include(../../css/vendor/angular-material/1.1.1/angular-material.min.css)
__opapp_include(../../css/vendor/radian/radian.min.css)
__opapp_include(../../js/vendor/ag-grid/dist/styles/ag-grid.css)
__opapp_include(../../js/vendor/ag-grid/dist/styles/theme-optinomic.css)
__opapp_include(../../css/vendor/mdi/1.7.22/css/materialdesignicons.min.css)
__opapp_include(../../css/optinomic/basic.css)
