__opapp_include(../../css/vendor/bootstrap/3.3.5/css/bootstrap.min.css)
__opapp_include(../../js/vendor/angular-grid/dist/angular-grid.css)
__opapp_include(../../js/vendor/angular-grid/dist/theme-fresh.css)
__opapp_include(../../css/vendor/mdi/css/materialdesignicons.min.css)
__opapp_include(../../css/optinomic/basic.css)
